import json
import os

from config.settings import ACTIVE_SYSTEM, OUTPUT_CHUNKS_DIR


def compile_sillytavern_lorebook(chunk_files, output_file, book_name):
    """
    Binds a list of JSON chunk files into a single, 
    import-ready SillyTavern V3 Lorebook.
    """
    if not chunk_files:
        print("  ❌ No JSON files to compile.")
        return

    # 2. Build the SillyTavern V3 Root Schema
    compiled_lorebook = {
        "name": book_name,
        "description": "Auto-generated by Python ETL Pipeline",
        "is_creation": False,
        "scan_depth": 50,
        "token_budget": 1500,
        "recursive_scanning": True,
        "extensions": {},
        "entries": {} # ST stores entries as a dictionary of stringified IDs
    }
    
    # Global counter to prevent ID collisions between chunks
    global_uid = 1
    
    for file_path in chunk_files:
        try:
            with open(file_path, encoding='utf-8') as f:
                data = json.load(f)
                
                # Extract the array of entries from the chunk
                entries = data.get('entries', data) if isinstance(data, dict) else data
                
                # Handle ST's dict-of-dicts format if the AI accidentally hallucinated it
                if isinstance(entries, dict):
                    entries_list = list(entries.values())
                else:
                    entries_list = entries
                    
                # 3. Clean and Re-index each entry
                for entry in entries_list:
                    if not isinstance(entry, dict):
                        continue
                        
                    # Update both 'id' and 'uid' fields to the new global count
                    entry['id'] = global_uid
                    entry['uid'] = global_uid
                    
                    # Ensure 'keys' exists and is properly formatted as a list
                    if 'keys' not in entry and 'key' in entry:
                        entry['keys'] = entry['key']
                        
                    entry.setdefault('constant', False)
                    entry.setdefault('selective', False)
                    entry.setdefault('order', 100)
                    entry.setdefault('position', 1)
                    entry.setdefault('disable', False)
                        
                    # Inject the cleaned entry into the master dictionary using the UID as the string key
                    compiled_lorebook['entries'][str(global_uid)] = entry
                    
                    global_uid += 1
                    
        except json.JSONDecodeError:
            print(f"  ⚠️ Skipping {file_path} - Invalid JSON syntax.")
        except Exception as e:
            print(f"  ❌ Error reading {file_path}: {e}")
            
    # 4. Write the final Master Lorebook
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(compiled_lorebook, f, indent=4)
        
    print(f"  ✅ Binding complete! {global_uid - 1} total mechanics compiled into '{output_file}'.")

if __name__ == "__main__":
    from pathlib import Path
    
    # 1. Grab all JSON files recursively from settings configuration directory
    chunks_path = Path(OUTPUT_CHUNKS_DIR)
    all_files = list(chunks_path.rglob("*.json")) if chunks_path.exists() else []
    
    # Fallback to local 'JSON_Lorebooks' if nothing is in the output dir
    if not all_files and os.path.exists("JSON_Lorebooks"):
        chunks_path = Path("JSON_Lorebooks")
        all_files = list(chunks_path.rglob("*.json"))

    # Group files by top-level subdirectory under input folder
    groups = {}
    for f in all_files:
        if "debug" in f.parts:
            continue
        try:
            rel_path = f.relative_to(chunks_path)
            parts = rel_path.parent.parts
        except ValueError:
            parts = ()
            
        group_name = parts[0] if parts else ACTIVE_SYSTEM
        groups.setdefault(group_name, []).append(f)
        
    if not groups:
        print(f"📭 No JSON files found in {OUTPUT_CHUNKS_DIR} (or fallback 'JSON_Lorebooks') to compile.")
        exit(0)
        
    for group_name, files in groups.items():
        output_filename = f"{group_name.replace(' ', '_')}_Master_Lorebook.json"
        book_name = f"{group_name} Core Rules"
        print(f"\n📦 Compiling Lorebook for group '{group_name}' ({len(files)} files)...")
        # Sort files alphabetically to preserve reading/rule sequence
        files_sorted = sorted([str(f) for f in files])
        compile_sillytavern_lorebook(
            chunk_files=files_sorted, 
            output_file=output_filename, 
            book_name=book_name
        )
